//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/Controls/ItemColliderControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ItemColliderControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ItemColliderControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ItemColliderControls"",
    ""maps"": [
        {
            ""name"": ""ItemColliderTool"",
            ""id"": ""a3a88a8a-28e3-4b8b-93cb-bfeda042a72f"",
            ""actions"": [
                {
                    ""name"": ""Click"",
                    ""type"": ""Button"",
                    ""id"": ""78192421-da24-4313-9c97-02d8877b7871"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MousePosition"",
                    ""type"": ""Value"",
                    ""id"": ""a6dc4d26-5d9e-4393-94c6-45d5d7d54904"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""37adf688-f2be-45ed-8fa4-b7d8a55aeab0"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8771cc96-3b07-4559-a3c1-da53dabcc62f"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // ItemColliderTool
        m_ItemColliderTool = asset.FindActionMap("ItemColliderTool", throwIfNotFound: true);
        m_ItemColliderTool_Click = m_ItemColliderTool.FindAction("Click", throwIfNotFound: true);
        m_ItemColliderTool_MousePosition = m_ItemColliderTool.FindAction("MousePosition", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // ItemColliderTool
    private readonly InputActionMap m_ItemColliderTool;
    private List<IItemColliderToolActions> m_ItemColliderToolActionsCallbackInterfaces = new List<IItemColliderToolActions>();
    private readonly InputAction m_ItemColliderTool_Click;
    private readonly InputAction m_ItemColliderTool_MousePosition;
    public struct ItemColliderToolActions
    {
        private @ItemColliderControls m_Wrapper;
        public ItemColliderToolActions(@ItemColliderControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Click => m_Wrapper.m_ItemColliderTool_Click;
        public InputAction @MousePosition => m_Wrapper.m_ItemColliderTool_MousePosition;
        public InputActionMap Get() { return m_Wrapper.m_ItemColliderTool; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ItemColliderToolActions set) { return set.Get(); }
        public void AddCallbacks(IItemColliderToolActions instance)
        {
            if (instance == null || m_Wrapper.m_ItemColliderToolActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ItemColliderToolActionsCallbackInterfaces.Add(instance);
            @Click.started += instance.OnClick;
            @Click.performed += instance.OnClick;
            @Click.canceled += instance.OnClick;
            @MousePosition.started += instance.OnMousePosition;
            @MousePosition.performed += instance.OnMousePosition;
            @MousePosition.canceled += instance.OnMousePosition;
        }

        private void UnregisterCallbacks(IItemColliderToolActions instance)
        {
            @Click.started -= instance.OnClick;
            @Click.performed -= instance.OnClick;
            @Click.canceled -= instance.OnClick;
            @MousePosition.started -= instance.OnMousePosition;
            @MousePosition.performed -= instance.OnMousePosition;
            @MousePosition.canceled -= instance.OnMousePosition;
        }

        public void RemoveCallbacks(IItemColliderToolActions instance)
        {
            if (m_Wrapper.m_ItemColliderToolActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IItemColliderToolActions instance)
        {
            foreach (var item in m_Wrapper.m_ItemColliderToolActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ItemColliderToolActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ItemColliderToolActions @ItemColliderTool => new ItemColliderToolActions(this);
    public interface IItemColliderToolActions
    {
        void OnClick(InputAction.CallbackContext context);
        void OnMousePosition(InputAction.CallbackContext context);
    }
}
